import type { Suite } from './types.js';

// Everyday phrasings of each v4 job type. Benchmark prompts alone teach a router
// what the test looks like, not what users type; these widen the examples a
// routing profile ships so live requests land in the right job type.
// Keep them different from any evaluation set used to measure routing.
export const NATURAL_EXAMPLES: Record<Suite, string[]> = {
  code: [
    'Write a function that merges two sorted arrays into one sorted array.',
    'Can you give me a Python script that renames every photo in a folder by its date taken?',
    'Write a Rust function that parses a semantic version string into its parts.',
    'Make me a React hook that tracks the window size.',
    'Write a PostgreSQL query that finds duplicate emails in the users table.',
    'I need a Java method that checks whether a string is a valid IPv4 address.',
    'Write a small Node script that reads a CSV and prints the average of the price column.',
    'Create a Python class for a bank account with deposit, withdraw and a balance history.',
    'Write a function to compute the moving average of a list with a given window size.',
    'Give me a PowerShell script that lists services that are stopped but set to automatic.',
    'Implement binary search in C and handle the empty-array case.',
    'Write a helper that formats a number of seconds as H:MM:SS.',
  ],
  repo: [
    'The build broke after my last commit and the logs point at the auth module. Can you find what I broke and fix it?',
    'Two tests in the payments folder fail intermittently. Look through the code, figure out the race condition and fix it.',
    'Our API returns 500 when the query string is empty. Track down the handler and fix it without changing the other endpoints.',
    'After upgrading the ORM, saving a user duplicates their addresses. Find the cause in the models and patch it.',
    'pytest says test_invoice_totals fails with an off-by-one. Read the billing package and fix the bug.',
    'The mobile app crashes on logout on Android only. Go through the code and find the null that causes it.',
    'Something in our cache layer returns stale data after updates. Investigate the service files and fix it, then run the tests.',
    'This function works for small inputs but times out on big ones. Find the slow part in the repo and fix it.',
    'The date picker shows the wrong month in some time zones. Find the bug in the utils and components and correct it.',
    'Our import script silently drops rows with accents. Find where the encoding goes wrong and fix it.',
    'A refactor broke the export feature. Compare the modules, find the regression and fix it so all tests pass.',
    'The linter passes but the app throws "undefined is not a function" on startup. Debug the project and fix it.',
  ],
  agent: [
    'Process today\'s refund requests: check each order against the return policy, issue the eligible refunds and reply to each customer.',
    'Clean up the CRM: find duplicate contacts, merge them, and assign any orphaned leads to the right sales rep.',
    'Onboard the new hire: create their accounts, add them to the right groups and schedule their first-week meetings.',
    'Go through the overdue invoices, send a reminder for each, and escalate anything over 60 days to finance.',
    'Reconcile this month\'s card transactions against the receipts and flag anything that doesn\'t match.',
    'Handle the support queue: answer what you can from the knowledge base and escalate the rest by priority.',
    'Plan the team offsite: check everyone\'s calendars, book a room that fits, and send the agenda.',
    'Audit user permissions: find accounts with admin access that haven\'t logged in for 90 days and revoke it, then report.',
    'Restock the store: check inventory levels, create purchase orders for anything below minimum and notify the suppliers.',
    'Review this week\'s job applications, reject the ones missing requirements and schedule interviews for the rest.',
    'Migrate the open tickets from the old tracker to the new one, keeping owners and due dates.',
    'Look up the customer\'s account, check why their payment failed, retry it and let them know the result.',
  ],
  fncall: [
    'Book a table for four at 7pm on Friday at the Italian place.',
    'Add milk and eggs to my shopping list.',
    'How much is 1,200 US dollars in euros?',
    'Start a 25-minute timer.',
    'Text Ben that I\'m running ten minutes late.',
    'What\'s the status of order 88213?',
    'Turn the heat up to 22 degrees in the bedroom.',
    'Schedule a call with Priya next Tuesday at 10am for 30 minutes.',
    'Look up tomorrow\'s forecast for Vancouver.',
    'Create a calendar event for the dentist on the 14th at 9:15.',
    'Play my focus playlist on the kitchen speaker.',
    'Find hotels in Montreal for two nights starting October 3rd.',
  ],
  reason: [
    'If I double a recipe that serves 6 but only have 5 eggs and it needs 3 per batch, how many people can I actually feed?',
    'Three workers can paint a fence in 6 hours; how long would five take at the same rate?',
    'What\'s the expected number of rolls to get a six on a fair die?',
    'A store marks up by 40% then discounts by 25%. What\'s the net change in price?',
    'How many ways can you choose a committee of 3 from 10 people if two of them refuse to serve together?',
    'If today is Thursday, what day of the week will it be 1,000 days from now?',
    'Solve for x: 3x + 7 = 2(x - 4) + 15, and show the steps.',
    'A car depreciates 15% a year. After how many full years is it worth less than half its price?',
    'Is it cheaper to buy 3 packs of 12 at $8.49 or 2 packs of 18 at $12.99 per egg?',
    'Knights always tell the truth and knaves always lie. A says "B is a knave", B says "we are both knights". Who is what?',
    'What\'s the shortest route that visits all four stops if the distances are A-B 5, A-C 7, B-C 3, B-D 6, C-D 4?',
    'A tank fills in 4 hours and drains in 6. Starting empty with both open, when is it full?',
  ],
  longdoc: [
    'Here\'s the full lease agreement. Who pays for repairs to the heating system, and what\'s the notice period to leave?',
    'Attached is our employee handbook. How many vacation days do people get after five years?',
    'Read this 60-page RFP and tell me the submission deadline and the three mandatory requirements.',
    'Based on the quarterly report below, which region grew fastest and by how much?',
    'In these server logs, when did the first timeout happen and which service threw it?',
    'Using the meeting minutes below, what did the board decide about the budget and who voted against?',
    'Here is the insurance policy. Is water damage from a burst pipe covered, and what\'s the deductible?',
    'From the research paper below, what sample size did they use and what was the main limitation?',
    'Going by this product manual, how do I reset the device to factory settings?',
    'In the transcript below, what did the customer say was the reason for cancelling?',
    'Scan this changelog and tell me which version first added SSO support.',
    'This spreadsheet export lists all shipments. Which carrier had the most late deliveries in August?',
  ],
  instruct: [
    'Write a tweet about our launch in under 200 characters with exactly two hashtags.',
    'Describe the product in three sentences, each starting with a different verb.',
    'Answer with just yes or no.',
    'Write a limerick about coffee. No other text.',
    'List five book titles as a markdown table with columns title and author only.',
    'Write an email subject line under 8 words, all in title case.',
    'Rewrite this paragraph in plain English at a grade 6 reading level, keeping it under 80 words.',
    'Give me a bulleted list of exactly four risks, each under ten words, no punctuation at the end.',
    'Write a haiku with the syllables 5-7-5 about autumn, and nothing else.',
    'Output a YAML config with keys host, port and debug set to false. No comments.',
    'Summarize the article in exactly 50 words.',
    'Write a slogan in all caps that includes the word "fast" exactly once.',
  ],
};
